In [40]:
import pandas as pd
import os
import re
from matplotlib import pyplot as plt
from utils import *

In [41]:
path_short = '../sMUC_logs_serial_300s'
path_long = '../sMUC_log_serial_3000s'

In [42]:
df_short = parse_serial_overview(path_short, 'Serial')
df_short

,name,Serial_result,Serial_memory,Serial_runtime
0,mchess_15.cnf,0,0.023136,299.97
1,ctl_4291_567_9_unsat.cnf,0,0.038654,299.82
2,af-synthesis_stb_50_140_1_unsat.cnf,0,0.045563,299.92
3,apn-sbox5-cut3-symmbreak.cnf,0,0.059841,299.97
4,x9-12035.sat.sanitized.cnf,0,0.036098,299.94
...,...,...,...,...
396,noL-11-2.sanitized.cnf,0,0.038643,299.97
397,x9-10084.sat.sanitized.cnf,-1,0.019932,145.85
398,crafted_n12_d6_c4_num23.cnf,0,0.351089,299.94
399,mdp-32-10-unsat.cnf,0,0.040680,299.96
400,urqh1c5x5.shuffled-as.sat03-1468.cnf.mis-103.d...,0,0.034328,300.94

In [43]:
df_long = parse_serial_overview(path_long, 'Serial')
df_long

,name,Serial_result,Serial_memory,Serial_runtime
0,constraints_18_0.5_2.sanitized.cnf,-1,0.276360,952.96
1,Nb44T6.cnf,0,1.032196,2999.86
2,cliquecolouring_n21_k6_c5.sanitized.cnf,0,0.125298,2999.84
3,2dlx_ca_bp_f_liveness.cnf,0,0.267033,2999.84
4,j3037_9_rggt_b.cnf,1,0.039291,480.25
...,...,...,...,...
231,fermat-931960058139995587.cnf,0,0.041546,3000.78
232,cliquecolouring_n13_k8_c7.sanitized.cnf,0,0.108971,3000.86
233,x9-12098.sat.sanitized.cnf,1,0.064003,1026.53
234,1-ET-512-K-110.sanitized.cnf,0,0.151630,2999.12
235,MASG0_72_keystream76_0.cnf,1,0.028622,1797.87

In [45]:
combined_data = {
    'name': [],
    'Serial_result': [],
    'Serial_memory': [],
    'Serial_runtime': []
}

for name in df_short['name']:
    row = df_long[df_long['name'] == name]
    if not len(row):
        row = df_short[df_short['name'] == name]
    
    #print(list(row['name'])[0])

    combined_data['name'].append(list(row['name'])[0])
    combined_data['Serial_result'].append(list(row['Serial_result'])[0])
    combined_data['Serial_memory'].append(list(row['Serial_memory'])[0])
    combined_data['Serial_runtime'].append(list(row['Serial_runtime'])[0])

df = pd.DataFrame(combined_data)
df

,name,Serial_result,Serial_memory,Serial_runtime
0,mchess_15.cnf,-1,0.032532,510.10
1,ctl_4291_567_9_unsat.cnf,-1,0.041626,884.40
2,af-synthesis_stb_50_140_1_unsat.cnf,-1,0.061958,2276.84
3,apn-sbox5-cut3-symmbreak.cnf,0,0.097157,2999.42
4,x9-12035.sat.sanitized.cnf,1,0.035927,420.57
...,...,...,...,...
396,noL-11-2.sanitized.cnf,1,0.063232,699.47
397,x9-10084.sat.sanitized.cnf,-1,0.019932,145.85
398,crafted_n12_d6_c4_num23.cnf,-1,0.349373,364.12
399,mdp-32-10-unsat.cnf,0,0.068459,3000.88
400,urqh1c5x5.shuffled-as.sat03-1468.cnf.mis-103.d...,0,0.083141,2999.87

In [46]:
df.to_csv('serial_kissat.csv', sep='\t')