In [2]:
import os
import re
import pandas as pd
import numpy as np

from matplotlib import pyplot as plt

from utils import *

In [3]:
df = pd.read_csv('track_2023_2024_database.csv', sep='\t')
df = df[df['track'].str.contains('main_2024')].reset_index(drop=True)
df = df.merge(pd.read_csv('benchmark_meta_data.csv', sep='\t'), how='inner', on='hash')
df.drop(columns=['hash', 'isohash', 'proceedings', 'minisat1m', 'author', 'track'], inplace=True)
df['name'] = df['filename']
df.drop(columns='filename', inplace=True)

cols = ['name', 'family', 'variables', 'clauses', 'result']
cols += list(set(df.columns.tolist()) - set(cols))
df = df[cols]

df

,name,family,variables,clauses,result,bytes,vcg_vdegree_max,balancevars_variance,cls4,balancevars_max,...,base_features_runtime,vg_degree_max,hornvars_entropy,invhornvars_min,cg_degree_entropy,invhornvars_variance,balancevars_entropy,cls2,hornvars_mean,balancecls_variance
0,lec_mult_KvW_12x11.sanitized.cnf,miter,5068,15159,unsat,217478,50,0.01,0,1.00,...,0,125,0.50,0,0.64,10.41,0.04,10044,3.98,0.17
1,mrpp_4x4#12_12.cnf,planning,2672,16408,unsat,260577,40,0.09,2288,1.00,...,0,124,0.90,0,0.89,81.17,0.53,7744,2.56,0.11
2,x9-10051.sat.sanitized.cnf,hamiltonian,500,4498,unsat,55761,24,0.00,98,0.33,...,0,64,0.02,0,0.69,3.62,0.00,4098,3.99,0.00
3,REGRandom-K4-L3-Seed40.sanitized.cnf,reg-n,22528,13231616,unsat,332485991,9217,0.08,0,0.80,...,63,8411147,0.00,0,0.52,6349111.40,0.00,2080768,1.00,0.00
4,linked_list_swap_contents_safety_unwind69.cnf,software-verification,2705815,33181429,unsat,839747623,19014,0.15,425543,1.00,...,123,84771,0.32,0,0.36,2511.36,0.92,28065666,12.42,0.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,j3045_4_mdd_bm1.cnf,scheduling,13043,52096,unsat,815410,103,0.10,1524,1.00,...,0,289,0.48,0,0.83,35.68,0.58,32061,3.40,0.15
396,constraints_17_0.4_2.sanitized.cnf,quantum-kochen-specker,2720,57086,unsat,29438620,9914,0.09,7820,0.67,...,6,1960186,0.36,0,0.74,3747.17,0.00,2448,2727.60,0.06
397,Break_unsat_16_27.xml.cnf,scheduling,31113,127845,unknown,2013340,34,0.08,144,1.00,...,0,184,0.70,0,0.71,33.21,1.00,120604,4.63,0.21
398,constraints_16_0.3_1.sanitized.cnf,quantum-kochen-specker,2240,21080,unsat,5793718,2386,0.08,6020,0.67,...,1,504179,0.37,0,0.73,3115.14,0.00,2040,633.90,0.10
399,1-ZC-512-K-61.sanitized.cnf,independent-set,30426,1003450,sat,16150576,400,0.02,2,0.95,...,2,1170,0.03,0,0.26,951.06,0.00,822839,6.86,0.03

In [4]:
# Instances of family 'argumentation'
df[df['family'] == 'argumentation']

,name,family,variables,clauses,result,bytes,vcg_vdegree_max,balancevars_variance,cls4,balancevars_max,...,base_features_runtime,vg_degree_max,hornvars_entropy,invhornvars_min,cg_degree_entropy,invhornvars_variance,balancevars_entropy,cls2,hornvars_mean,balancecls_variance
8,stb_495_168.apx_2_DC-AD.cnf,argumentation,990,20950,unsat,254974,114,0.01,4,0.49,...,0,669,0.89,0,0.74,229.00,0.00,20462,34.01,0.23
90,ER_500_30_3.apx_1_DC-ST.cnf,argumentation,1002,113965,unsat,1397126,471,0.01,0,0.32,...,0,8243,0.93,0,0.81,5920.09,0.00,113463,188.37,0.23
118,ER_400_20_4.apx_2_DC-AD.cnf,argumentation,802,49151,unsat,597982,271,0.01,0,0.34,...,1,3209,0.94,0,0.81,1793.37,0.00,48749,100.85,0.23
121,ER_400_20_7.apx_2_DC-AD.cnf,argumentation,802,48038,unsat,583793,262,0.01,0,0.32,...,1,2841,0.94,0,0.80,1713.85,0.00,47636,98.54,0.23
135,ER_400_20_4.apx_1_DC-AD.cnf,argumentation,802,49151,unsat,597982,271,0.01,0,0.34,...,0,3209,0.94,0,0.80,1793.42,0.00,48749,100.85,0.23
137,stb_418_125.apx_1_DC-ST.cnf,argumentation,836,17335,unsat,208872,101,0.01,1,0.51,...,0,530,0.89,0,0.74,204.00,0.00,16920,33.45,0.23
147,WS_500_16_90_70.apx_2_DC-AD.cnf,argumentation,1000,13001,unsat,156885,78,0.01,9,0.44,...,0,284,0.88,0,0.71,82.85,0.00,12502,20.48,0.23
160,stb_531_83.apx_1_DC-ST.cnf,argumentation,1062,20345,unsat,248033,96,0.01,4,0.52,...,0,484,0.88,0,0.72,173.85,0.00,19823,30.86,0.23
173,stb_588_138.apx_1_DC-AD.cnf,argumentation,1176,13062,unsat,160602,67,0.01,19,1.00,...,0,237,0.83,0,0.72,65.22,0.01,12476,17.32,0.23
203,stb_531_83.apx_2_DC-ST.cnf,argumentation,1062,20345,unsat,248033,96,0.01,4,0.52,...,0,484,0.88,0,0.72,173.85,0.00,19823,30.86,0.23
226,stable-300-0.1-20-98765432130020.cnf,argumentation,300,17540,sat,1083005,1532,0.00,0,0.16,...,1,47340,0.99,0,0.93,67.43,0.00,9063,876.82,0.00
240,WS_500_16_70_10.apx_1_DC-ST.cnf,argumentation,1000,13501,unsat,161673,64,0.01,9,0.48,...,0,247,0.87,0,0.70,82.43,0.00,13001,21.48,0.24
249,WS_500_16_70_10.apx_2_DC-AD.cnf,argumentation,1000,13001,unsat,156785,63,0.01,9,0.44,...,0,245,0.87,0,0.71,82.45,0.00,12501,20.48,0.23
257,stb_495_168.apx_1_DC-AD.cnf,argumentation,990,20950,unsat,254974,114,0.01,4,0.49,...,0,669,0.89,0,0.74,228.99,0.00,20462,34.01,0.23
277,stb_418_125.apx_2_DC-AD.cnf,argumentation,836,16917,unsat,204804,100,0.01,1,0.49,...,0,528,0.89,0,0.74,203.99,0.00,16502,32.45,0.23
294,stb_588_138.apx_1_DC-ST.cnf,argumentation,1176,13650,unsat,166547,68,0.01,19,0.67,...,0,239,0.83,0,0.72,65.22,0.00,13064,18.32,0.24
333,ER_400_20_7.apx_2_DC-ST.cnf,argumentation,802,48439,unsat,587692,263,0.01,0,0.33,...,0,2843,0.94,0,0.80,1713.85,0.00,48037,99.54,0.23
336,stb_418_125.apx_1_DC-AD.cnf,argumentation,836,16917,unsat,204803,100,0.01,1,0.49,...,0,528,0.89,0,0.74,204.00,0.00,16502,32.45,0.23
360,ER_400_20_4.apx_2_DC-ST.cnf,argumentation,802,49552,unsat,601881,272,0.01,0,0.35,...,0,3211,0.94,0,0.80,1793.37,0.00,49150,101.85,0.23
365,ER_500_30_3.apx_2_DC-AD.cnf,argumentation,1002,113464,unsat,1392224,470,0.01,0,0.32,...,0,8241,0.93,0,0.80,5919.97,0.00,112962,187.37,0.22
377,ER_400_20_7.apx_1_DC-AD.cnf,argumentation,802,48038,unsat,583793,262,0.01,0,0.32,...,0,2841,0.94,0,0.80,1713.94,0.00,47636,98.54,0.23

In [7]:
# Instances of Family 'tseitin-formulas'
df[df['family'] == 'tseitin-formulas']

,name,family,variables,clauses,result,bytes,vcg_vdegree_max,balancevars_variance,cls4,balancevars_max,...,base_features_runtime,vg_degree_max,hornvars_entropy,invhornvars_min,cg_degree_entropy,invhornvars_variance,balancevars_entropy,cls2,hornvars_mean,balancecls_variance
9,marg5x5.shuffled-as.sat03-1455.cnf,tseitin-formulas,105,512,unsat,8931,32,0.00,192,1.0,...,0,160,0.83,0,0.90,6.48,0.00,0,5.26,0.09
34,urqh1c5x5.shuffled-as.sat03-1468.cnf.mis-103.d...,tseitin-formulas,13313,26968,unsat,410415,116,0.02,0,1.0,...,0,334,0.07,0,0.50,94.56,0.17,13912,2.08,0.08
71,tseitin_d3_n158.sanitized.cnf,tseitin-formulas,237,632,unsat,8907,8,0.00,0,1.0,...,0,24,0.78,0,0.00,2.17,0.00,0,4.08,0.05
102,tseitingrid6x200_shuffled.cnf,tseitin-formulas,2400,9600,unsat,212623,16,0.00,9600,1.0,...,1,64,0.74,0,0.00,4.26,0.00,0,5.00,0.14
104,tseitin_grid_n11_m20.sanitized.cnf,tseitin-formulas,409,1520,unsat,27881,16,0.00,1296,1.0,...,0,64,0.75,0,0.61,4.28,0.00,8,4.97,0.12
148,tseitin_d3_n174.sanitized.cnf,tseitin-formulas,261,696,unsat,9899,8,0.00,0,1.0,...,0,24,0.75,0,0.00,1.91,0.00,0,4.17,0.05
263,urq45.cnf,tseitin-formulas,74,694,unsat,15757,128,0.00,48,1.0,...,0,896,0.88,0,0.86,12.60,0.00,2,6.75,0.06
310,tseitin_d3_n162.sanitized.cnf,tseitin-formulas,243,648,unsat,9155,8,0.00,0,1.0,...,0,24,0.76,0,0.00,2.03,0.00,0,4.28,0.05